---
title: "final project"
output: html_document
---

## data preparation

```{r}
rm(list = ls())
setwd("~/601final")
library(xlsx)
## data preprocessing 
set_b = read.csv("data/Set_b.csv", header = TRUE)
set_c = read.csv("data/Set_c.csv", header = TRUE) # set c has TP53
tp53 = read.xlsx("data/TP53.xlsx",sheetIndex = 1)##TP53
set_b = set_b[-which(set_b$response == 0),]
set_c = set_c[-which(set_c$response == 0),] # delete y=0
set_b_scale = data.frame(scale(set_b[,-1]))
set_b_scale$response = set_b$response
set_c_scale = data.frame(scale(set_c[,-1]))
set_c_scale$response = set_c$response # scale X

tp53 =tp53[-which(tp53$response == 0),] # delete the observation which has response equal to 0
tp53_scale = data.frame(scale(tp53[,-1]))

#View(set_c);View(set_b)
set_combine<-merge(set_b,set_c)
# set_combine = set_b
# set_combine[,length(set_b):(length(set_b)+length(set_c))] = set_c
set_combine_scale = data.frame(scale(set_combine[,-1]))
set_combine_scale$response = set_combine$response

# name_b = names(set_b_scale)
# name_c = names(set_c_scale)
# a = rep(0, length(name_c))
# for(i in 1:length(name_b)){
#   for(j in 1:length(name_c)){
#     if(name_c[j] == name_b[i]){
#       a[j] = 1
#     }
#   }
# }
# index = which(a == 1)
# set_combine_scale = set_combine_scale[,-(length(set_b_scale)+index-1)]
```

## Set b, response

```{r}
## transformation
suppressMessages(library(MASS))
suppressMessages(library(bestglm))
suppressMessages(library(dplyr))
hist(set_b_scale$response)
hist(log(set_b_scale$response))
set_b_log = mutate(y=log(response),.data = set_b_scale)#new y
set_b_log = select(set_b_log,-response)
```

```{r}
## full model
m_b = lm(response~., data = set_b_scale)
layout(matrix(data = c(1,2,3,4), ncol = 2, byrow = TRUE))
plot(m_b)
layout(1)
m0_b = lm(y ~ ., data = set_b_log)
layout(matrix(data = c(1,2,3,4), ncol = 2, byrow = TRUE))
plot(m0_b)
layout(1)

## model selection by AIC
require(car)
m1_b = lm(y ~ 1, data = set_b_log)#initial model
n = dim(set_b_log)[1]

# forward
b_aic_forward = step(object = m1_b, scope = formula(m0_b), direction="forward",trace = 0) 
summary(b_aic_forward)
plot(b_aic_forward, which = 4)
outlierTest(b_aic_forward)
which(abs(rstudent(b_aic_forward)) >= qt(0.05/2, dim(set_b_log)[1] - dim(set_b_log)[2] - 1, lower.tail = FALSE))

# backward
b_aic_backward = step(m0_b, direction="backward",trace = 0) 
summary(b_aic_backward) # largest adj-Rsquared
plot(b_aic_backward, which = 4)
outlierTest(b_aic_backward)
which(abs(rstudent(b_aic_backward)) >= qt(0.05/2, dim(set_b_log)[1] - dim(set_b_log)[2] - 1, lower.tail = FALSE))

#stepwise
b_aic_stepwise = step(object = m1_b, scope = formula(m0_b), direction="both",trace = 0) 
summary(b_aic_stepwise)
plot(b_aic_stepwise, which = 4)
outlierTest(b_aic_stepwise)
which(abs(rstudent(b_aic_stepwise)) >= qt(0.05/2, dim(set_b_log)[1] - dim(set_b_log)[2] - 1, lower.tail = FALSE))


## model selection by BIC
b_bic_forward = step(object = m1_b, scope = formula(m0_b), direction="forward", k = log(n)) # forward
summary(b_bic_forward)
plot(b_bic_forward, which = 4)
outlierTest(b_bic_forward)
which(abs(rstudent(b_bic_forward)) >= qt(0.05/2, dim(set_b_log)[1] - dim(set_b_log)[2] - 1, lower.tail = FALSE))

b_bic_backward = step(m0_b, direction="backward", k = log(n)) # backward
summary(b_bic_backward)
plot(b_bic_backward, which = 4)
outlierTest(b_bic_backward)
which(abs(rstudent(b_bic_backward)) >= qt(0.05/2, dim(set_b_log)[1] - dim(set_b_log)[2] - 1, lower.tail = FALSE))

b_bic_stepwise = step(object = m1_b, scope = formula(m0_b), direction="both", k = log(n)) #stepwise
summary(b_bic_stepwise)
plot(b_bic_stepwise, which = 4)
outlierTest(b_bic_stepwise)
which(abs(rstudent(b_bic_stepwise)) >= qt(0.05/2, dim(set_b_log)[1] - dim(set_b_log)[2] - 1, lower.tail = FALSE))

## model selection by Mallow's cp

## Cross Validation
require(DAAG)
b_aic_forward_cv = cv.lm(data = set_b_log, form.lm = y ~ BCL7C + ATG12 + HOXA9 + PYY + FNDC4 + PROM1 + 
    SPINK1 + NPAS3 + BRWD2 + GPR64 + MRPL49 + AAK1 + CIDEA + 
    OCLN + COL4A4 + GTF3C4 + DYNC1LI1 + F2R + PMM2 + FPGS + KREMEN2 + 
    ZNF492 + SCARF1 + MATK + AMBP + KIAA1199, m = 10,printit = FALSE) #1.22
mean((b_aic_forward_cv$cvpred-b_aic_forward_cv$y)^2)

b_aic_backward_cv = cv.lm(data = set_b_log, form.lm = y ~ RAD23B + FMO1 + PABPC3 + GOLPH3L + EDG5 + ASCL2 + 
    RPP21 + NEK11 + HBXIP + HOXC10 + RPGRIP1 + OCLN + MGLL + 
    NPC2 + EVL + MRPL49 + KIAA1199 + HNRPA3 + GPC4 + FPGS + CIDEA + 
    ULBP1 + GUCY1B3 + TOMM40 + ZNF492 + MATK + C16orf57 + ZBED2 + 
    BCL7C + PRKCQ + C5orf13 + KREMEN2 + H2AFY + RFK + TAF9B + 
    PALM + GSTK1 + PYY + AAK1 + HSPA14 + C11orf10 + ATP7A + TGFBR3 + 
    SFRS16 + BRWD2 + PGRMC2 + EIF4E + FNDC4 + SCNN1B + SPINK1 + 
    YARS + FADS2 + GPR143 + GTF3C4 + PMM2 + NPAS3 + HOXA9 + KBTBD10 + 
    IDH2, m =10,printit = FALSE) #1.22
mean((b_aic_backward_cv$cvpred-b_aic_backward_cv$y)^2)

b_aic_stepwise_cv = cv.lm(data = set_b_log, form.lm = y ~ BCL7C + HOXA9 + PYY + FNDC4 + PROM1 + SPINK1 +     NPAS3 + BRWD2 + GPR64 + MRPL49 + AAK1 + CIDEA + OCLN + COL4A4 + 
    KREMEN2 + PMM2 + GTF3C4 + FPGS + F2R + SCARF1 + ZNF492 + 
    AMBP + MATK + KIAA1199, m = 10,printit = FALSE) #1.21
mean((b_aic_stepwise_cv$cvpred-b_aic_stepwise_cv$y)^2)


b_bic_forward_cv = cv.lm(data = set_b_log, form.lm = y ~ BCL7C + ATG12, m = 10,printit = FALSE) # 1.28
mean((b_bic_forward_cv$cvpred-b_bic_forward_cv$y)^2)


b_bic_backward_cv = cv.lm(data = set_b_log, form.lm = y ~ BCL7C + BRWD2 + NPAS3, m = 10,printit = FALSE) # 1.27
mean((b_bic_backward_cv$cvpred-b_bic_backward_cv$y)^2)

b_bic_stepwise_cv = cv.lm(data = set_b_log, form.lm = y ~ BCL7C + ATG12, m = 10,printit = FALSE) # 1.28
mean((b_bic_stepwise_cv$cvpred-b_bic_stepwise_cv$y)^2)

## PCR
require(pls)
b_princomp = princomp(set_b_log[,-201])#delete y
#summary(b_princomp)
#loadings(b_princomp)
plot(b_princomp)

b_pca = pcr(y ~ ., ncomp = 30, data = set_b_log, validation = "CV")
summary(b_pca)
b_pcr = lm(y ~ b_pca$scores, set_b_log)
summary(b_pcr)

b_pca_dataframe = data.frame(unclass(b_pca$scores))
b_pca_dataframe$y = set_b_log$y
b_pcr_cv = cv.lm(data = b_pca_dataframe, form.lm = y ~ ., m = 10) #105

which(abs(drop(coef(b_pca)))> 0.02)
cv.lm(data = set_b_log[c(abs(drop(coef(b_pca)))> 0.02,TRUE)], 
      form.lm = y ~ .,m=10,
      printit = FALSE)#117

## PLS
b_pls = plsr(y ~ .,ncomp = 30,scale = TRUE, data = set_b_log, validation = "CV", method="oscorespls")
summary(b_pls)


b_pls_lm = lm(y~b_pls$scores,set_b_log)
summary(b_pls_lm)

b_pls_dataframe = data.frame(unclass(b_pls$scores))
b_pls_dataframe$y = set_b_log$y
b_pls_cv = cv.lm(data = b_pls_dataframe, form.lm = y ~ ., m = 10) #128


which(abs(drop(coef(b_pls)))> 0.15)
cv.lm(data = set_b_log[c(abs(drop(coef(b_pls)))> 0.15,TRUE)], 
      form.lm = y ~ .,m=10,
      printit = FALSE)#113
```

## Set C, response 
```{r,eval=FALSE}
## transformation
hist(set_c_scale$response)
hist(log(set_c_scale$response))
set_c_log = mutate(y=log(response),.data = set_c_scale)#new y
set_c_log = select(set_c_log,-response)

## fitting full model
m_c = lm(response~., data = set_c_scale)
layout(matrix(data = c(1,2,3,4), ncol = 2, byrow = TRUE))
plot(m_c)
layout(1)
m0_c = lm(y ~ ., data = set_c_log)
layout(matrix(data = c(1,2,3,4), ncol = 2, byrow = TRUE))
plot(m0_c)
layout(1)

## model selection
m1_c = lm(y ~ 1, data = set_c_log)
n = dim(set_c_log)[1]

c_aic_forward = step(object = m1_c, scope = formula(m0_c), direction="forward") # forward
summary(c_aic_forward)
plot(c_aic_forward, which = 4)
outlierTest(c_aic_forward)
which(abs(rstudent(c_aic_forward)) >= qt(0.05/2, dim(set_c_log)[1] - dim(set_c_log)[2] - 1, lower.tail = FALSE))

c_aic_backward = step(m0_c, direction="backward") # backward
summary(c_aic_backward) # largest adj-Rsquared 0.164
plot(c_aic_backward, which = 4)
outlierTest(c_aic_backward)
which(abs(rstudent(c_aic_backward)) >= qt(0.05/2, dim(set_c_log)[1] - dim(set_c_log)[2] - 1, lower.tail = FALSE))

c_aic_stepwise = step(object = m1_c, scope = formula(m0_c), direction="both") #stepwise
summary(c_aic_stepwise)
plot(c_aic_stepwise, which = 4)
outlierTest(c_aic_stepwise)
which(abs(rstudent(c_aic_stepwise)) >= qt(0.05/2, dim(set_c_log)[1] - dim(set_c_log)[2] - 1, lower.tail = FALSE))

c_bic_forward = step(object = m1_c, scope = formula(m0_c), direction="forward", k = log(n)) # forward
summary(c_bic_forward)
plot(c_bic_forward, which = 4)
outlierTest(c_bic_forward)
which(abs(rstudent(c_bic_forward)) >= qt(0.05/2, dim(set_c_log)[1] - dim(set_c_log)[2] - 1, lower.tail = FALSE))

c_bic_backward = step(m0_c, direction="backward", k = log(n)) # backward
summary(c_bic_backward)
plot(c_bic_backward, which = 4)
outlierTest(c_bic_backward)
which(abs(rstudent(c_bic_backward)) >= qt(0.05/2, dim(set_c_log)[1] - dim(set_c_log)[2] - 1, lower.tail = FALSE))

c_bic_stepwise = step(object = m1_c, scope = formula(m0_c), direction="both", k = log(n)) #stepwise
summary(c_bic_stepwise)
plot(c_bic_stepwise, which = 4)
outlierTest(c_bic_stepwise)
which(abs(rstudent(c_bic_stepwise)) >= qt(0.05/2, dim(set_c_log)[1] - dim(set_c_log)[2] - 1, lower.tail = FALSE))

#Mallow's cp

## Cross Validation
c_aic_forward_cv = cv.lm(data = set_c_log, form.lm = y ~ KIR3DX1 + GALNT14 + CYP2W1 + FNDC4 + CACNA2D2 +     PYY + FLG + PLCD1 + ABCD3 + C1orf69 + ALKBH4 + SOSTDC1 + 
    FLJ20309 + SNAPC2 + PCDHA9 + SMC5 + PLXNB1 + VDR + SMARCC1 + 
    ANP32E + SLC35C2 + PLCG1 + PITX1 + ING3 + tcag7.1314 + SPINK1 + 
    ZNF250 + NXT2 + AIFM1, m = 10) #1.2
c_aic_backward_cv = cv.lm(data = set_c_log, form.lm = y ~ TP53 + PRDM2 + SYNGR3 + FLG + SMARCC1 + PCDHA9 + 
    LRRC15 + NELL2 + SHROOM2 + RPUSD2 + PLCG1 + CEL + SEPW1 + 
    PLEKHF2 + APITD1 + RPS13 + GSTA3 + SMC5 + GALNT14 + SNAPC2 + 
    C9orf167 + RPLP2 + MRPL24 + MRPL44 + C20orf43 + PYY + ALKBH4 + 
    POLR3B + SPINK1 + PLCD1 + KIR3DX1 + C2 + ASPN + C1orf69 + 
    BUB1 + VDR + FNDC4 + NXT2 + LAPTM4B + DKFZP566E164 + CCND1 + 
    DLGAP2 + PLXNB1 + tcag7.1314 + TRIM15 + SLC35C2, m =10) #1.22
c_aic_stepwise_cv = cv.lm(data = set_c_log, form.lm = y ~ KIR3DX1 + GALNT14 + CYP2W1 + FNDC4 + CACNA2D2 + 
    PYY + FLG + PLCD1 + ABCD3 + C1orf69 + ALKBH4 + SOSTDC1 + 
    SNAPC2 + PCDHA9 + SMC5 + PLXNB1 + VDR + SMARCC1 + ANP32E + 
    SLC35C2 + PLCG1 + PITX1 + ING3 + tcag7.1314 + SPINK1 + ZNF250 + 
    NXT2 + AIFM1 + MRPL44 + RPS13 + DLGAP2, m = 10) #1.2

c_bic_forward_cv = cv.lm(data = set_c_log, form.lm = y ~ KIR3DX1, m = 10) # 1.29
#for bic, three methods have the same outcome.

## PCR
c_princomp = princomp(set_c_log[,-201])
summary(c_princomp)
loadings(c_princomp)
plot(c_princomp)

c_pca = pcr(y ~ ., ncomp = 30,scale = TRUE, data = set_c_log, validation = "CV")
summary(c_pca)
c_pcr = lm(y ~ c_pca$scores, set_c_log)
summary(c_pcr)
c_pca_dataframe = data.frame(unclass(c_pca$scores))
c_pca_dataframe$y = set_c_log$y
c_pcr_cv = cv.lm(data = c_pca_dataframe, form.lm = y ~ ., m = 10) #132

## PLS
c_pls = plsr(y ~ .,ncomp = 30,scale = TRUE, data = set_c_log, validation = "CV", method="oscorespls")
summary(c_pls)
drop(coef(c_pls))

c_pls_lm = lm(y~c_pls$scores,set_c_log)
summary(c_pls_lm)

c_pls_dataframe = data.frame(unclass(c_pls$scores))
c_pls_dataframe$y = set_c_log$y
c_pls_cv = cv.lm(data = c_pls_dataframe, form.lm = y ~ ., m = 10) #112

```

## Set b, TP53 

```{r,eval=FALSE}

set_b_t = set_b_log[,-201]
names(tp53_scale) = "TP53"
set_b_t$TP53 = tp53_scale$TP53

## fitting full model
m0_b_t = lm(TP53 ~ ., data = set_b_t)
layout(matrix(data = c(1,2,3,4), ncol = 2, byrow = TRUE))
plot(m0_b_t)
layout(1)

## model selection (BIC: favoring simpler models)
m1_b_t = lm(TP53 ~ 1, data = set_b_t)
n = dim(set_b_t)[1]

b_aic_forward_t = step(object = m1_b_t, scope = formula(m0_b_t), direction="forward") # forward
summary(b_aic_forward_t) # 0.388
plot(b_aic_forward_t, which = 4)
outlierTest(b_aic_forward_t)
which(abs(rstudent(b_aic_forward_t)) >= qt(0.05/2, dim(set_b_t)[1] - dim(set_b_t)[2] - 1, lower.tail = FALSE))

b_aic_backward_t = step(m0_b_t, direction="backward") # backward
summary(b_aic_backward_t) # 0.402
plot(b_aic_backward_t, which = 4)
outlierTest(b_aic_backward_t)
which(abs(rstudent(b_aic_backward_t)) >= qt(0.05/2, dim(set_b_t)[1] - dim(set_b_t)[2] - 1, lower.tail = FALSE))

b_aic_stepwise_t = step(object = m1_b_t, scope = formula(m0_b_t), direction="both") #stepwise
summary(b_aic_stepwise_t) # 0.393
plot(b_aic_stepwise_t, which = 4)
outlierTest(b_aic_stepwise_t)
which(abs(rstudent(b_aic_stepwise_t)) >= qt(0.05/2, dim(set_b_t)[1] - dim(set_b_t)[2] - 1, lower.tail = FALSE))



b_bic_forward_t = step(object = m1_b_t, scope = formula(m0_b_t), direction="forward", k = log(n)) # forward
summary(b_bic_forward_t) # 0.249
plot(b_bic_forward_t, which = 4)
outlierTest(b_bic_forward_t)
which(abs(rstudent(b_bic_forward_t)) >= qt(0.05/2, dim(set_b_t)[1] - dim(set_b_t)[2] - 1, lower.tail = FALSE))

b_bic_backward_t = step(m0_b_t, direction="backward", k = log(n)) # backward
summary(b_bic_backward_t) # 0.284
plot(b_bic_backward_t, which = 4)
outlierTest(b_bic_backward_t)
which(abs(rstudent(b_bic_backward_t)) >= qt(0.05/2, dim(set_b_t)[1] - dim(set_b_t)[2] - 1, lower.tail = FALSE))

b_bic_stepwise_t = step(object = m1_b_t, scope = formula(m0_b_t), direction="both", k = log(n)) #stepwise
summary(b_bic_stepwise_t) # 0.243
plot(b_bic_stepwise_t, which = 4)
outlierTest(b_bic_stepwise_t)
which(abs(rstudent(b_bic_stepwise_t)) >= qt(0.05/2, dim(set_b_t)[1] - dim(set_b_t)[2] - 1, lower.tail = FALSE))

#Mallow's cp

## Cross Validation
b_aic_forward_cv_t = cv.lm(data = set_b_t, form.lm = TP53 ~ PFN1 + C6orf130 + HBXIP + NDUFB8 + ZBED2 + 
    ZNF197 + ASCL2 + MYO7B + TMEM38B + RABL5 + FAM128A + LITAF + 
    SLC6A8 + C1orf54 + C16orf57 + THRB + G0S2 + KLF10 + DNAJB5 + 
    FPGS + HOXC10 + HOXA9 + SEMA3B + ARHGEF12 + TAF4 + ZC3H13 + 
    AURKB + NOL1 + RBM12B + RPGRIP1 + PYY + MATK + KIAA0586 + 
    PPM1H + HNRNPU + AMBP + OR2F2 + NADSYN1 + GM2A + KREMEN2 + 
    KLHDC3 + NAP1L4 + DYNC1LI1 + ENO1 + SLC19A1 + RRP1 + S100A4 + 
    GUCY1B3 + MAD2L1 + PALM + OCLN + RFK + CADM3 + PDCD1LG2 + 
    SCNN1B, m = 10) #0.701
b_aic_backward_cv_t = cv.lm(data = set_b_t, form.lm = TP53 ~ SLC6A8 + ATM + SEMA3B + AURKB + ASCL2 + ISG20L1 + 
    RPP21 + SIVA1 + DNAJB5 + HBXIP + ARHGEF12 + HOXC10 + OR51E2 + 
    AMBP + TAF4 + RPGRIP1 + CANT1 + OCLN + RRP1 + ZC3H13 + TTLL12 + 
    KIAA1199 + SLC19A1 + FPGS + GUCY1B3 + TTK + RABL5 + HPGD + 
    MATK + C16orf57 + CINP + KLF10 + LOC374395 + PDCD1LG2 + C5orf13 + 
    KREMEN2 + H2AFY + RFK + PALM + NDUFB8 + ENO1 + KLHDC3 + PYY + 
    G0S2 + MYO7B + FAM128A + SCARF1 + ATP7A + NOL1 + C5orf5 + 
    SDCCAG3 + PFN1 + LMO3 + S100A4 + C6orf130 + HNRNPU + KIAA0586 + 
    DYNC1LI1 + IKBKB + TMEM38B + MAD2L1 + GM2A + KIAA1704 + C1orf54 + 
    SLC24A3 + THRB + HOXA9 + IDH2 + SYNJ2 + RBM12B, m =10) #0.723
b_aic_stepwise_cv_t = cv.lm(data = set_b_t, form.lm = TP53 ~ PFN1 + C6orf130 + HBXIP + NDUFB8 + ZBED2 + 
    ZNF197 + ASCL2 + MYO7B + TMEM38B + RABL5 + FAM128A + LITAF + 
    SLC6A8 + C1orf54 + C16orf57 + THRB + G0S2 + KLF10 + DNAJB5 + 
    FPGS + HOXC10 + HOXA9 + SEMA3B + ARHGEF12 + TAF4 + ZC3H13 + 
    AURKB + NOL1 + RBM12B + RPGRIP1 + PYY + MATK + KIAA0586 + 
    PPM1H + HNRNPU + AMBP + NADSYN1 + GM2A + KREMEN2 + KLHDC3 + 
    NAP1L4 + DYNC1LI1 + ENO1 + SLC19A1 + RRP1 + S100A4 + GUCY1B3 + 
    MAD2L1 + PALM + P18SRP + ATP7A + IKBKB + TNKS + RFK + PDCD1LG2 + 
    HPGD + LOC374395, m = 10) # 0.702

b_bic_forward_cv_t = cv.lm(data = set_b_t, form.lm = TP53 ~ PFN1 + C6orf130 + HBXIP + NDUFB8 + ZBED2 + 
    ZNF197 + ASCL2 + MYO7B + TMEM38B + RABL5 + FAM128A + LITAF + 
    SLC6A8 + C1orf54 + C16orf57, m = 10) # 0.769
b_bic_backward_cv_t = cv.lm(data = set_b_t, form.lm = TP53 ~ SLC6A8 + AURKB + ASCL2 + DNAJB5 + HOXC10 + 
    AMBP + TAF4 + OCLN + RRP1 + ZC3H13 + SLC19A1 + FPGS + RABL5 + 
    C16orf57 + KLF10 + NDUFB8 + G0S2 + MYO7B + FAM128A + C6orf130 + 
    TMEM38B + MAD2L1 + GM2A + THRB + RBM12B, m = 10) # 0.759
b_bic_stepwise_cv_t = cv.lm(data = set_b_t, form.lm = TP53 ~ PFN1 + C6orf130 + HBXIP + NDUFB8 + ZBED2 + 
    ZNF197 + ASCL2 + MYO7B + TMEM38B + FAM128A + LITAF + SLC6A8 + 
    C1orf54 + C16orf57, m = 10) # 0.774


## PCR
b_princomp_t = princomp(set_b_t[,-201])
summary(b_princomp_t)
loadings(b_princomp_t)
plot(b_princomp_t)

b_pca_t = pcr(TP53 ~ ., ncomp = 30,scale = TRUE, data = set_b_t, validation = "CV")
summary(b_pca_t)
b_pcr_t = lm(TP53 ~ b_pca_t$scores, set_b_t)
summary(b_pcr_t)
b_pca_dataframe_t = data.frame(unclass(b_pca_t$scores))
b_pca_dataframe_t$TP53 = set_b_t$TP53
b_pcr_cv_t = cv.lm(data = b_pca_dataframe_t, form.lm = TP53 ~ ., m = 10) #1.08

## PLS
b_pls_t = plsr(TP53 ~ .,ncomp = 30,scale = TRUE, data = set_b_t, validation = "CV", method="oscorespls")
summary(b_pls_t)
drop(coef(b_pls_t))

b_pls_lm_t = lm(TP53 ~ b_pls_t$scores,set_b_t)
summary(b_pls_lm_t)

b_pls_dataframe_t = data.frame(unclass(b_pls_t$scores))
b_pls_dataframe_t$TP53 = set_b_t$TP53
b_pls_cv_t = cv.lm(data = b_pls_dataframe_t, form.lm = TP53 ~ ., m = 10) #0.763

```

## Set C, TP53 
```{r,eval=FALSE}
set_c_t = set_c_scale[,-201]

## fitting full model
m0_c_t = lm(TP53 ~ ., data = set_c_t)
layout(matrix(data = c(1,2,3,4), ncol = 2, byrow = TRUE))
plot(m0_c_t)
layout(1)

## model selection
m1_c_t = lm(TP53 ~ 1, data = set_c_t)
n = dim(set_c_t)[1]

c_aic_forward_t = step(object = m1_c_t, scope = formula(m0_c_t), direction="forward") # forward
summary(c_aic_forward_t) # 0.292
plot(c_aic_forward_t, which = 4)
outlierTest(c_aic_forward_t)
which(abs(rstudent(c_aic_forward_t)) >= qt(0.05/2, dim(set_c_t)[1] - dim(set_c_t)[2] - 1, lower.tail = FALSE))

c_aic_backward_t = step(m0_c_t, direction="backward") # backward
summary(c_aic_backward_t) # 0.297
plot(c_aic_backward_t, which = 4)
outlierTest(c_aic_backward_t)
which(abs(rstudent(c_aic_backward_t)) >= qt(0.05/2, dim(set_c_t)[1] - dim(set_c_t)[2] - 1, lower.tail = FALSE))

c_aic_stepwise_t = step(object = m1_c_t, scope = formula(m0_c_t), direction="both") #stepwise
summary(c_aic_stepwise_t) # 0.284
plot(c_aic_stepwise_t, which = 4)
outlierTest(c_aic_stepwise_t)
which(abs(rstudent(c_aic_stepwise_t)) >= qt(0.05/2, dim(set_c_t)[1] - dim(set_c_t)[2] - 1, lower.tail = FALSE))



c_bic_forward_t = step(object = m1_c_t, scope = formula(m0_c_t), direction="forward", k = log(n)) # forward
summary(c_bic_forward_t) # 0.124
plot(c_bic_forward_t, which = 4)
outlierTest(c_bic_forward_t)
which(abs(rstudent(c_bic_forward_t)) >= qt(0.05/2, dim(set_c_t)[1] - dim(set_c_t)[2] - 1, lower.tail = FALSE))

c_bic_backward_t = step(m0_c_t, direction="backward", k = log(n)) # backward
summary(c_bic_backward_t) # 0.199
plot(c_bic_backward_t, which = 4)
outlierTest(c_bic_backward_t)
which(abs(rstudent(c_bic_backward_t)) >= qt(0.05/2, dim(set_c_t)[1] - dim(set_c_t)[2] - 1, lower.tail = FALSE))

c_bic_stepwise_t = step(object = m1_c_t, scope = formula(m0_c_t), direction="both", k = log(n)) #stepwise
summary(c_bic_stepwise_t) # 0.124
plot(c_bic_stepwise_t, which = 4)
outlierTest(c_bic_stepwise_t)
which(abs(rstudent(c_bic_stepwise_t)) >= qt(0.05/2, dim(set_c_t)[1] - dim(set_c_t)[2] - 1, lower.tail = FALSE))

#Mallow's cp

## Cross Validation
c_aic_forward_cv_t = cv.lm(data = set_c_t, form.lm = TP53 ~ YIPF3 + RRP12 + BRE + GK + SCML1 + DVL3 + 
    C13orf18 + PHF10 + MLF1 + THAP10 + SOCS6 + OXCT1 + SLC25A11 + 
    PLCD1 + FASTK + ORM1 + CXCL14 + PYY + CST3 + RANBP10 + MAT1A + 
    SNX17 + NXT2 + CACNA2D2 + KIAA1012 + KIDINS220 + TARBP2 + 
    PLEKHF2 + PEX13 + AKR1D1 + tcag7.1314 + RPS13 + ALKBH4 + 
    RPLP2 + SECISBP2 + MLPH + SCLY + CEL + ATF7IP + RBM16 + BAT2 + 
    DR1 + SPINK1 + IL12RB1 + PLCG1 + PITX1 + PIGC + SETD3, m = 10) # 0.778
c_aic_backward_cv_t = cv.lm(data = set_c_t, form.lm = TP53 ~ THAP10 + EXOC7 + KCNMB2 + DVL3 + FBLN5 + 
    CIR + ORM1 + HDAC3 + SCML1 + PLCG1 + RWDD2A + KIDINS220 + 
    SNX17 + CEL + PLEKHF2 + SLC25A11 + APITD1 + RPS13 + MOSC1 + 
    ATF7IP + MLPH + DNAJA3 + CXCL14 + NUP85 + SOCS6 + ABCA2 + 
    OXCT1 + KIR2DL4 + PYY + NRBP1 + C13orf18 + SLC16A4 + CST3 + 
    MAT1A + TBC1D12 + PIGC + KIAA1012 + GK + RANBP10 + FASTK + 
    SCLY + TK1 + SLC1A6 + NXT2 + PEX13 + DKFZP566E164 + PHF10 + 
    IQCC + AKR1D1 + tcag7.1314 + CRYBA2 + SLC46A3 + DR1 + CACNA2D2, m =10) #0.801
c_aic_stepwise_cv_t = cv.lm(data = set_c_t, form.lm = TP53 ~ RRP12 + GK + SCML1 + DVL3 + C13orf18 + PHF10 + 
    MLF1 + THAP10 + SOCS6 + OXCT1 + SLC25A11 + FASTK + ORM1 + 
    CXCL14 + PYY + CST3 + RANBP10 + MAT1A + SNX17 + NXT2 + CACNA2D2 + 
    KIAA1012 + KIDINS220 + TARBP2 + PLEKHF2 + PEX13 + AKR1D1 + 
    RPS13 + ALKBH4 + RPLP2 + SECISBP2 + ATF7IP + SETD3 + RBM16 + 
    BAT2 + PIGC + MAN2A2 + MLPH + SCLY, m = 10) #0.771

c_bic_forward_cv_t = cv.lm(data = set_c_t, form.lm = TP53 ~ YIPF3 + RRP12 + BRE + GK + SCML1 + DVL3, m = 10) # 0.888
c_bic_backward_cv_t = cv.lm(data = set_c_t, form.lm = TP53 ~ THAP10 + SCML1 + KIDINS220 + SLC25A11 + SOCS6 + 
    OXCT1 + PYY + C13orf18 + CST3 + MAT1A + GK + RANBP10 + PEX13 + 
    AKR1D1 + tcag7.1314 + CACNA2D2, m = 10) # 0.831
c_bic_stepwise_cv_t = cv.lm(data = set_c_t, form.lm = TP53 ~ YIPF3 + RRP12 + BRE + GK + SCML1 + DVL3, m = 10) # 0.888
#for bic, three methods have the same outcome.

## PCR
grep(pattern = "TP53", x = names(set_c_log))
c_princomp_t = princomp(set_c_t[,-4])
summary(c_princomp_t)
loadings(c_princomp_t)
plot(c_princomp_t)

c_pca_t = pcr(TP53 ~ ., ncomp = 30,scale = TRUE, data = set_c_t, validation = "CV")
summary(c_pca_t)
c_pcr_t = lm(TP53 ~ c_pca_t$scores, set_c_t)
summary(c_pcr_t)
c_pca_dataframe_t = data.frame(unclass(c_pca_t$scores))
c_pca_dataframe_t$TP53 = set_c_t$TP53
c_pcr_cv_t = cv.lm(data = c_pca_dataframe_t, form.lm = TP53 ~ ., m = 10) # 1.09

## PLS
c_pls_t = plsr(TP53 ~ .,ncomp = 30,scale = TRUE, data = set_c_t, validation = "CV", method="oscorespls")
summary(c_pls_t)
drop(coef(c_pls_t))

c_pls_lm_t = lm(TP53 ~ c_pls_t$scores,set_c_t)
summary(c_pls_lm_t)

c_pls_dataframe_t = data.frame(unclass(c_pls_t$scores))
c_pls_dataframe_t$TP53 = set_c_t$TP53
c_pls_cv_t = cv.lm(data = c_pls_dataframe_t, form.lm = TP53 ~ ., m = 10) #0.737

```

## 3.GLM

*choose subdata by AIC model:b_aic_stepwise*  


```{r}
bestmodel<-b_aic_stepwise
```


```{r}
dd.log<- bestmodel$model
dd.log<- cbind(select(dd.log,-y),select(dd.log,y))
```


*logit*

```{r,eval=TRUE}
hist(dd.log$y)#take 6.5 as thrshold
threshold<-6.5
dd.log<-mutate(dd.log,y=ifelse(y<6.5,0,1))
#logit<-glm(y~.,dd.log,family = binomial)

bic.log<-bestglm(Xy = dd.log,
             family = binomial,
             IC = "BIC") # data should not be too big
bic$BestModel
```

## 4.GMC  

find the optimal subset of X which make the $GMC(Y|X_{sub})$ or $GMC(Y|G(X_{sub}))$ largest!

subset: from the previous results  
link function(g())


$$Maximize~~GMC(Y|g(X))-lambda (lasso)$$

$$g(x)=x\\ linear~~ model$$ 

take variable and initial beta from AIC model: b_aic_stepwise    

```{r}
g1<-function(x){
  return(x)
}
source("GMC.R")
xb<- bestmodel$fitted.values
data<-cbind(g1(xb),bestmodel$model$y)#X,Y
GMC(data)#(GMC(X|Y),GMC(Y|X))
```


```{r,eval=TRUE}
#optimal beta
(initials<-bestmodel$coefficients)#initial beta  
require(parallel)
require(reshape2)
#optimal beta
rnge<- seq(0,2,by = 0.5)
lambda1<- as.vector(sapply(rnge, function(x) rep(x,length(rnge))))
lambda2<- rnge
lambda.set <- rbind(lambda1, lambda2)
lambda.set <- as.data.frame(lambda.set);dim(lambda.set)

findopt<-function(lambda){
  lambda1<-lambda[1];lambda2<-lambda[2]
  fn<-function(beta){
  xb= as.matrix(bestmodel$model[-1]) %*% beta[-1]+beta[1]
  fit.n<-g1(xb)
  resid<-bestmodel$model$y- fit.n
  data<-cbind(fit.n,bestmodel$model$y)#X,Y
  return(-GMC(data)[2]+ lambda1*var(fit.n,resid)+lambda2*sum(abs(beta)))
 }
  
  opt<-optim(par = initials, fn =fn, method = "Nelder-Mead" )
  return(c(lambda,opt$par,-opt$value))
}

OptEveryLambda<-mclapply(lambda.set, FUN = findopt,mc.cores=4)
class(OptEveryLambda)
save(OptEveryLambda, file = "OptEveryLambda.RData")
#colnames(OpetEveryLambda)[c(1,2,)]<- c("lambda1","lambda2","GMC(Y|G(X))")

fn<-function(beta){
  xb= as.matrix(bestmodel$model[-1]) %*% beta[-1]+beta[1]
  data<-cbind(g1(xb),bestmodel$model$y)#X,Y
  return(-GMC(data)[2]+ lambda*sum(beta))#(GMC(X|Y),GMC(Y|X))
  
}
opt<-optim(par = initials, fn =fn, method = "Nelder-Mead" )
opt$par
-opt$value#optimal GMC(Y|X)
```  


$$g(x)= e^x Poisson~~ regression$$  

use variable from bic model 

```{r,eval=TRUE}
g2<-function(x){
  return(exp(x))
}
poisson<- glm(y ~ ., family="poisson", data=bestmodel$model)
initials<- poisson$coefficients

data<-cbind(poisson$fitted.values,bestmodel$model$y)#X,Y
GMC(data)#(GMC(X|Y),GMC(Y|X)) 
```


```{r,eval=TRUE}
#require(parallel)
#optimal beta

findopt<-function(lambda){
  lambda1<-lambda[1];lambda2<-lambda[2]
  fn<-function(beta){
  xb= as.matrix(bestmodel$model[-1]) %*% beta[-1]+beta[1]
  fit.n<-g2(xb)
  resid<-bestmodel$model$y- fit.n
  data<-cbind(fit.n,bestmodel$model$y)#X,Y
  return(-GMC(data)[2]+ lambda1*var(fit.n,resid)+lambda2*sum(abs(beta)))
 }
  
  opt<-optim(par = initials, fn =fn, method = "Nelder-Mead" )
  return(c(lambda,opt$par,-opt$value))
}

OptEveryLambda2<-mclapply(lambda.set, FUN = findopt,mc.cores=4)
class(OptEveryLambda2)
save(OptEveryLambda2, file = "OptEveryLambda2.RData")
# fn<-function(beta){
#   xb= as.matrix(bestmodel$model[-1]) %*% beta[-1]+beta[1]
#   
#   data<-cbind(g2(xb),bestmodel$model$y)#X,Y
#   return(-GMC(data)[2]+ lambda*sum(beta))#(GMC(X|Y),GMC(Y|X))
# }
# opt<-optim(par = initials, fn =fn, method = "Nelder-Mead" )
# opt$par
# -opt$value#optimal GMC
```
