---
title: "601final"
author: "Dingxian Cao"
date: "December 3, 2015"
output: html_document
---

office:
M:1:30pm
F:11:00am

```{r}
setwd("~/601final")
library(xlsx)
set.b<-read.csv(file = "data/Set_b.csv",header = T)
set.c<-read.csv(file = "data/Set_c.csv",header = T)
yy<- read.xlsx("data/TP53.xlsx",sheetIndex = 1)##TP53

#View(set.b);View(set.c)
#names(set.b)[names(set.b) %in% names(set.c)]

suppressMessages(library(MASS))


```

##1.transformation  

```{r}

suppressMessages(library(bestglm))
suppressMessages(library(dplyr))
dd<-mutate(y=log(response),.data = set.b)#new y
dd<- select(dd,-response)
dd<-filter(dd,!(is.infinite(dd$y)))#new data  

```  


# 2. linear model selection(AIC,BIC,CP,CV)
```{r}
aic<-bestglm(Xy = dd,
             family = gaussian,
             IC = "AIC", 
             method = "forward") 
names(aic$BestModel$model) 
summary(aic)

bic<-bestglm(Xy = dd,
             family = gaussian,
             IC = "BIC", 
             method = "forward") 
bic$BestModel

pairs(bic$BestModel$model)
```  

### CV1
```{r}
options(warn = -1)
library(DAAG)
aic.cv<-CVlm(data = aic$BestModel$model, y ~ .,m = 5,printit = FALSE)
(aic.pe <- mean((aic.cv$cvpred-aic.cv$y)^2))

bic.cv<-CVlm(data = bic$BestModel$model, y ~ .,m = 5,printit = FALSE)
(bic.pe <- mean((bic.cv$cvpred-bic.cv$y)^2))
```  


>BIC IS better

## PCR  

```{r}
suppressMessages(library(pls))
pca<-pcr(y ~ ., ncomp = 10,scale = TRUE,
    data = dd, validation = "CV")
summary(pca)
pca.lm<-lm(y~pca$scores,dd)
summary(pca.lm)
```  

## PLS  

```{r}
pls<-plsr(y ~ .,ncomp = 10,scale = TRUE,
          data = dd, validation = "CV"
          ,method="oscorespls")

summary(pls)
#drop(coef(pls))

pls.lm<-lm(y~pls$scores,dd)
summary(pls.lm)
``` 

## Ridge  

### CV2

## 3.GLM

*choose subdata by BIC model*  

```{r}
dd.log<-bic$BestModel$model
dd.log<- cbind(select(dd.log,-y),select(dd.log,y))
```


*logit*

```{r}
hist(dd.log$y)#take 6.5 as thrshold
threshold<-6.5
dd.log<-mutate(dd.log,y=ifelse(y<6.5,0,1))
#logit<-glm(y~.,dd.log,family = binomial)

bic.log<-bestglm(Xy = dd.log,
             family = binomial,
             IC = "BIC") # data's too big
bic$BestModel

```

## 4.GMC  

find the optimal subset of X which make the $GMC(Y|X_{sub})$ or $GMC(Y|G(X_{sub}))$ largest!

subset: from the previous results  
link function(g())


$$g(x)=x\\ linear~~ model$$ 

take variable and initial beta from BIC model    

```{r}
g1<-function(x){
  return(x)
}
source("GMC.R")
xb<- bic$BestModel$fitted.values
data<-cbind(g1(xb),bic$BestModel$model$y)#X,Y
GMC(data)#(GMC(X|Y),GMC(Y|X))
```


```{r}
#optimal beta
(initials<-bic$BestModel$coefficients)#initial beta  
fn<-function(beta){
  xb= as.matrix(bic$BestModel$model[-1]) %*% beta[-1]+beta[1]
  data<-cbind(g1(xb),bic$BestModel$model$y)#X,Y
  return(-GMC(data)[2])#(GMC(X|Y),GMC(Y|X))
  
}
opt<-optim(par = initials, fn =fn, method = "Nelder-Mead" )
opt$par
-opt$value#optimal GMC
```  


$$g(x)= e^x Poisson~~ regression$$  

use variable from bic model 

```{r}
g2<-function(x){
  return(exp(x))
}
poisson<- glm(y ~ ., family="poisson", data=bic$BestModel$model)
initials<- poisson$coefficients

data<-cbind(poisson$fitted.values,bic$BestModel$model$y)#X,Y
GMC(data)#(GMC(X|Y),GMC(Y|X)) 
```


```{r}
#optimal beta
fn<-function(beta){
  xb= as.matrix(bic$BestModel$model[-1]) %*% beta[-1]+beta[1]
  
  data<-cbind(g2(xb),bic$BestModel$model$y)#X,Y
  return(-GMC(data)[2])#(GMC(X|Y),GMC(Y|X))
}
opt<-optim(par = initials, fn =fn, method = "Nelder-Mead" )
opt$par
-opt$value#optimal GMC
```







